[package]
name = "mujoco-rs"
version = "2.1.0+mj-3.3.7"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "A Rust wrapper around the MuJoCo C library, with a native simple viewer (re-)written in Rust."
readme = "README.md"
repository = "https://github.com/davidhozic/mujoco-rs"
keywords = ["MuJoCo", "Viewer", "Bindings", "Wrapper"]
categories = ["simulation", "science::robotics", "api-bindings"]
homepage = "https://crates.io/crates/mujoco-rs"
documentation = "https://docs.rs/mujoco-rs/"

exclude = ["src/cpp/*", ".gitignore", ".gitmodules", "mujoco/*"]

[package.metadata.docs.rs]
all-features = true


[features]
viewer = ["dep:bitflags", "dep:glutin", "dep:winit", "dep:glutin-winit"]
viewer-ui = ["viewer", "dep:egui-winit", "dep:egui_glow", "dep:egui"]
renderer = ["dep:bitflags", "dep:glutin", "dep:winit", "dep:glutin-winit", "dep:png"]
cpp-viewer = []

ffi-regenerate = ["dep:regex", "dep:bindgen"]  # Generate the ffi bindings. Only used for updating the committed ``mujoco_c`` module. 
default = ["viewer", "viewer-ui", "renderer"]

[dependencies]
bitflags = {version = "2.9.4", optional = true}
png = {version = "0.18.0", optional = true}
paste = "1.0.15"

# Rendering dependencies
glutin = {version = "0.32.3", optional = true}
winit = {version = "0.30.12", optional = true}
glutin-winit = {version = "0.5.0", optional = true}
# Viewer's user interface dependencies
egui-winit = {version = "0.33.0", default-features = false, features = ["wayland", "x11"], optional = true}
egui_glow = {version = "0.33.0", features = ["x11", "winit", "wayland", "egui-winit"], optional = true}
egui = {version = "0.33.0", optional = true}

[build-dependencies]
bindgen = {version = "0.71.1", optional = true}
pkg-config = "0.3"
regex = {version = "1.11.2", optional = true}

# Automatic download dependencies
ureq = "3.1.4"

[target.'cfg(unix)'.build-dependencies]
flate2 = "1.1.5"
tar = "0.4.44"

[target.'cfg(windows)'.build-dependencies]
zip = { version = "6.0.0", default-features = false, features = ["deflate"] }

[dev-dependencies]
rand = "0.9.2"
