name: Test MuJoCo-rs (OpenGL included)

on:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]  
  push:
    branches:
      - "feature/ci-tests"


permissions:
  contents: read

jobs:
  test:
    name: Test (lib-only) on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        features: ["renderer auto-download-mujoco", "auto-download-mujoco"]
      fail-fast: false

    env:
      MUJOCO_DOWNLOAD_DIR: "/usr/lib/"
      RUST_BACKTRACE: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache cargo (registry/git and target)
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install Rust (rustup + stable toolchain)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal

      - name: cargo test
        run: cargo test --lib --features ${{matrix.features}} --verbose
        shell: bash
