name: Test MuJoCo-rs (OpenGL included)

on:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]  
  push:
    branches:
      - "feature/ci-tests"


permissions:
  contents: read

jobs:
  test:
    name: "Test library on ${{ matrix.os }} with features: $${{join(matrix.features, ' ')}}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        features: [
          ["renderer", "renderer-winit-fallback", "auto-download-mujoco"],
          ["auto-download-mujoco"]
        ]
      fail-fast: false

    env:
      RUST_BACKTRACE: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Cargo.lock
        run: cargo generate-lockfile

      - name: Prepare features string
        run: |
          echo "MJRS_FEATURES=\"${{join(matrix.features, ' ')}}\"" >> $GITHUB_ENV
        shell: bash

      - name: Cache cargo (registry/git and target)
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{join(matrix.features, '')}}-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Mesa (OpenGL + EGL) on Ubuntu
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          libgl1-mesa-dev \
          libegl1-mesa-dev \
          libgles2-mesa-dev \
          mesa-utils

          export LIBGL_ALWAYS_SOFTWARE=1
          export MESA_LOADER_DRIVER_OVERRIDE=llvmpipe

      - name: Set MUJOCO_DOWNLOAD_DIR
        shell: bash
        run: |
          if [ "$RUNNER_OS" = "Windows" ]; then
            # PowerShell alternative for Windows
            ABS_PATH=$(powershell -Command "Resolve-Path . | Select-Object -ExpandProperty Path")
          else
            ABS_PATH=$(realpath .)
          fi
          echo "MUJOCO_DOWNLOAD_DIR=$ABS_PATH" >> $GITHUB_ENV

      - name: cargo build (debug)
        run: cargo build --lib --features ${{env.MJRS_FEATURES}} --no-default-features

      - name: cargo release (debug)
        run: cargo build --release --lib --features ${{env.MJRS_FEATURES}} --no-default-features

      - name: Setup LD_LIBRARY_PATH on Linux
        if: runner.os == 'Linux'
        run: |
          MUJOCO_DIR=$(ls | grep '^mujoco-' | head -n1)
          echo "LD_LIBRARY_PATH=$PWD/$MUJOCO_DIR/lib/:$LD_LIBRARY_PATH" >> $GITHUB_ENV
        shell: bash

      - name: Copy mujoco.dll on Windows
        if: runner.os == 'Windows'
        run: |
          MUJOCO_DIR=$(ls | grep '^mujoco-' | head -n1)
          cp $PWD/$MUJOCO_DIR/bin/mujoco.dll .
        shell: bash

      - name: cargo test (debug)
        run: cargo test --lib --features ${{env.MJRS_FEATURES}} --no-default-features

      - name: cargo test (release)
        run: cargo test --release --lib --features ${{env.MJRS_FEATURES}} --no-default-features
     
      - name: Run a rendering test
        if: contains(matrix.features, 'renderer') && runner.os == 'Linux'
        run: cargo run --release --example renderer --features ${{env.MJRS_FEATURES}} --no-default-features
