name: Test MuJoCo-rs (OpenGL included)

on:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]  
  push:
    branches:
      - "feature/ci-tests"


permissions:
  contents: read

jobs:
  test:
    name: Test (lib-only) on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        features: ["renderer auto-download-mujoco", "auto-download-mujoco"]
      fail-fast: false

    env:
      RUST_BACKTRACE: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache cargo (registry/git and target)
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install Rust (rustup + stable toolchain)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal

      - name: Set MuJoCo download location environmental variable
        run: echo "MUJOCO_DOWNLOAD_DIR=$(realpath .)" >> $GITHUB_ENV
        shell: bash

      - name: cargo build (debug)
        run: cargo build --lib --features "${{matrix.features}}"

      - name: cargo release (debug)
        run: cargo build --release --lib --features "${{matrix.features}}"

      - name: Setup LD_LIBRARY_PATH on Linux
        if: runner.os == 'Linux'
        run: |
          MUJOCO_DIR=$(ls | grep '^mujoco-' | head -n1)
          echo "LD_LIBRARY_PATH=$PWD/$MUJOCO_DIR/lib/:$LD_LIBRARY_PATH" >> $GITHUB_ENV
        shell: bash

      - name: cargo test (debug)
        run: cargo test --lib --features "${{matrix.features}}"

      - name: cargo test (release)
        run: cargo test --release --lib --features "${{matrix.features}}"
